### ISSUE TITLE
app-editors/vscode-9999: Please use node.js versions >=16.14.x and <17

### ISSUE THREAD

**Issue by darkbasic** [PF4Public/gentoo-overlay#155]
```
>>> Configuring source in /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999 ...
 * Installing node_modules ...
yarn config v1.22.19
success Set "disable-self-update-check" to "true".
Done in 0.11s.
yarn config v1.22.19
success Set "nodedir" to "/usr/include/electron-18/node".
Done in 0.18s.
yarn install v1.22.19
$ node build/npm/preinstall.js
*** Please use node.js versions >=16.14.x and <17.
```

```
~ # emerge -pv nodejs

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] net-libs/nodejs-16.14.2:0/16::gentoo  USE="icu inspector npm snapshot ssl system-icu system-ssl -debug -doc -lto -pax-kernel -systemtap -test" 0 KiB
```

**Comment by PF4Public** [comment]
I prepend PATH with `/usr/$(get_libdir)/electron-${ELECTRON_SLOT}`, which results in electron's `node` being the preferred one. I think I've done so to try and avoid the dependency on nodejs or maybe for it to build natives for electron's node instead of the system-installed one. electron-18 has node-16.13.2, which is why you got that error.

Honestly saying I don't know what would be the proper fix. On one hand it would be nice to not depend on nodejs at all, but there are things, that just do not work with electron's node.

**Comment by darkbasic** [comment]
node.js should be slotted, but it isn't so... I've already compiled chromium 102 on ppc64 so I'll just update the electron 19 ebuild for the moment.
