### ISSUE TITLE
media-libs/flac-1.4.1

### ISSUE THREAD

**Issue by mrturcot** [PF4Public/gentoo-overlay#174]
I just updated to media-libs/flac-1.4.1 and had some preserved libs associated with ungoogled-chromium-bin namely libFLAC.so.8. However @preserved-rebuild didn't resolve it the issue. So I removed ungoogled-chromium-bin then re-emerged it and now getting this during install 

```
 * QA Notice: Unresolved soname dependencies:
 *
 *      /opt/chromium-browser/chrome: libFLAC.so.8
 *
```

And running "chromium" from terminal I'm getting 

```
➜ chromium                              
chromium-browser: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
```

Is this something I should seek help from the Gentoo forum? Or is this a legit issue?

**Comment by PF4Public** [comment]
Sorry, I couldn't have replied earlier because I needed to disconnect and take a break for some time as I haven't had a vacation for about 3 years.

That is a typical issue with binary packages unfortunately and @preserved-rebuild is useless on them. I would suggest not removing a binary with preserved libs as it keeps it functioning until an updated binary is emerged which no longer depends on an older version. W.r.t. ungoogled-chromium-bin specifically you need to wait until I spin up my build-KVM-guests, update all the chroots and finally compile the latest version. I've disabled everything ([updater-bot](https://github.com/PF4Public/gentoo-overlay/commits?author=oegniwgrogklfepog%5Bbot%5D) being the sole exception) due to leaving for a vacation.

Also see #120 #161 #124 #105 #89 and so on.

**Comment by mrturcot** [comment]
Got it thanks so much! I upgraded to testing source ebuild of ungoogled-chromium. Really appreciate the project! Hope you had a dope vacation 😎✌️

**Comment by PF4Public** [comment]
FYI: [latest binary is ready](https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-106.0.5249.119.ebuild)
