### ISSUE TITLE
app-editors/vscode-1.75.1: Cannot activate the 'Prettier - Code formatter' extension because it depends on an unknown 'vscode.npm' extension

### ISSUE THREAD

**Issue by darkbasic** [PF4Public/gentoo-overlay#203]
```
[ebuild   R   ~] app-editors/vscode-1.75.1::pf4public  USE="-badge-providers -build-online -electron-20 -electron-21 -electron-22 -insiders -liveshare -openvsx -substitute-urls"
```

I get this message when opening vscode, not sure why the extension fails.
Arch is ppc64le.

**Comment by PF4Public** [comment]
I remember it either crashed vscode upon enabling or showing extension info, therefore [I've removed it since then](https://github.com/PF4Public/gentoo-overlay/blob/98cb0ced13e5396dde148a3af2b3c781db331c5b/app-editors/vscode/vscode-9999.ebuild#L116-L118). But if you could confirm it works, I'd gladly restore it.

**Comment by PF4Public** [comment]
So, does it work or not?

**Comment by darkbasic** [comment]
I've tried to re-add the extensions but unfortunately it didn't complete the build that way.

**Comment by PF4Public** [comment]
It is an upstream issue. You can follow it here: https://github.com/microsoft/vscode/issues/181598

Seems to be an easy fix though. After fixing I can enable npm without issues and even Prettier runs:
![image](https://user-images.githubusercontent.com/10319700/236349743-819601f8-c38a-4ece-af02-bf8a87385f69.png)

**Comment by PF4Public** [comment]
I'll close this issue since there is upstream one
