### ISSUE TITLE
Patches for x11-libs/libva-vdpau-driver to enable Chromium vaapi for nvidia users

### ISSUE THREAD

**Issue by dagraver** [PF4Public/gentoo-overlay#28]
Patches to enable Chromium vaapi for nvidia users.

The current (public) version of libva-vdpau-driver does not have all functionality to enable vaapi  for Chromium to work.

The attached patches implements these features to enable, at least, h264 acceleration to work. Not tested with other codecs.

Tested with a GeForce GTX-770 (440.59) on Gentoo.

Credits go to Saikrishna Arcot (https://launchpad.net/~saiarcot895/) , et al.

[fallback-x.patch.txt](https://github.com/PF4Public/gentoo-overlay/files/4223899/fallback-x.patch.txt)
[implement-vaquerysurfaceattributes.patch.txt](https://github.com/PF4Public/gentoo-overlay/files/4223900/implement-vaquerysurfaceattributes.patch.txt)

**Comment by dagraver** [comment]
I forgot. The only known 'issue' is that sometimes the video will turn black on pause; it will fix itself on resume.

**Comment by PF4Public** [comment]
Hi

Thank you very much for your efforts

I have however some concerns:
* Who's going to be maintaining these patches? I do not have any Nvidia hardware, so that this is quite unrealistic for me
* Cannot these patches be applied as [User patches](https://wiki.gentoo.org/wiki//etc/portage/patches) locally?

**Comment by dagraver** [comment]
1) Since the vdpau-wrapper for vaapi is pretty much abandoned, I doubt there will any updates

2) They can.

I looked through the vaapi patches you use and the patch hard-disables it for NVIDIA (vendor 0x10de) anyway, so my request was pointless regardless.

My apologies for wasting your time. Closing.

**Comment by PF4Public** [comment]
>They can.

If those patches could be applied locally, I'd suggest applying them that way.

>Since the vdpau-wrapper for vaapi is pretty much abandoned, I doubt there will any updates

If that's true, keeping patches in `/etc/portage/patches` will serve the purpose just fine.

>I looked through the vaapi patches you use and the patch hard-disables it for NVIDIA (vendor 0x10de) anyway, so my request was pointless regardless.

I may be wrong, but `chrome://flags/#ignore-gpu-blacklist` might be useful to change this. Alternatively I may remove `+      "vendor_id": "0x10de",` from the patch if that makes sense.

There is actually [chromium-fix-vaapi-r2.patch](../blob/master/www-client/ungoogled-chromium/files/chromium-fix-vaapi-r2.patch), which was applied until I [removed it](https://github.com/PF4Public/gentoo-overlay/commit/0341be6f13d437eb7557d8c7950d08012c1e1d1f#diff-7091c1b10df4452d9cf4b177aa166090L258). I've removed it because it was unclear to me, what effect it has on non-vdpau users and whether it solves anything for vdpau users at the first place. 

It might just happen so, that even if one applies patches for `x11-libs/libva-vdpau-driver`, [chromium-fix-vaapi-r2.patch](../blob/master/www-client/ungoogled-chromium/files/chromium-fix-vaapi-r2.patch) is still needed to be applied. If that's the case, just let me know, we can think through, how to use/apply it properly.

**Comment by PF4Public** [comment]
I have taken new Arch vaapi patches. Including [vdpau patches](https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium/files/vdpau-support.patch).
@dagraver does it make any difference for you?
