### ISSUE TITLE
www-client/ungoogled-chromium-bin with wayland support

### ISSUE THREAD

**Issue by VPaulV** [PF4Public/gentoo-overlay#288]
Hi guys, thank you for the great overlay. Would it be possible to add wayland support for the ungoogled-chromium-bin?

**Comment by PF4Public** [comment]
It would've been great if you [used the search first](https://github.com/PF4Public/gentoo-overlay/issues?q=is%3Aissue+%22wayland+support%22).

Please have a look at https://github.com/PF4Public/gentoo-overlay/issues/107. Feel free to reopen this issue if you believe something had changed since then.
